### ISSUE TITLE
Deploying version 1.1.11 on NPM

### ISSUE THREAD

**Issue by gilles-crealp** [pixari/vue-i18n-extract#100]
Can you please deploy version 1.1.11 on NPM so we can use your plugin with `-a` (bug #78) on Windows?

**Comment by pixari** [comment]
Sure @gilles-crealp!
I'm going to do it.

**Comment by gilles-crealp** [comment]
Thank you!

**Comment by pixari** [comment]
Done! Thank you, @gilles-crealp !
