### ISSUE TITLE
Inconsistent extraction to js

### ISSUE THREAD

**Issue by last-partizan** [pixari/vue-i18n-extract#103]
When this plugin reads content from js, it uses `eval(fs.readFileSync(langPath, 'utf8'));`

But when writing, it uses 
```
        const jsFile = `export default ${stringifiedContent}; \n`;
```

So, it can not read it's own files.

```
export default {
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by pixari** [comment]
Is this bug still valid?

**Comment by last-partizan** [comment]
@pixari yes, version 1.2.0 using `module.exports = ` when reading, and `export default` when writing.

**Comment by last-partizan** [comment]
`yarn vue-i18n-extract -a -v TestComponent.vue -l locale/en.js`

just run something like this two times.

**Comment by pixari** [comment]
I'm going to have a look :)

**Comment by Spittal** [comment]
Whoops this was my bad. Fixed now!

**Comment by Oleksii14** [comment]
Any updates?

**Comment by theunclehonnor** [comment]
Most likely, there is no support for es6 modules, read more here https://github.com/pixari/vue-i18n-extract/issues/142
