### ISSUE TITLE
-ci option does not work as expected

### ISSUE THREAD

**Issue by last-partizan** [pixari/vue-i18n-extract#115]
There is this code in tests:

```
      expect((await runCLI([
        'report',
        '-v',
        `'./fixtures/vue-files/**/*.?(vue|js)'`,
        '-l',
        `'./fixtures/language-files/**/*.?(json|yml|yaml)'`,
        '-o',
        `'/dev/null'`,
        '-a',
        '-ci',
      ])).code).toBe(0);
```

But, test fixtures do contain missing keys. So, when you run command manually, you see this:

```
> yarn vue-i18n-extract report -v 'tests/unit/fixtures/vue-files/**/*.?(vue|js)' -l 'tests/unit/fixtures/language-files/**/*.?(json|yml|yaml)' -ci
missing keys: 
┌─────────┬──────────────────────────────────┬──────┬────────────────────────────────────────────────────────────┬──────────┐
│ (index) │               path               │ line │                            file                            │ language │
├─────────┼──────────────────────────────────┼──────┼────────────────────────────────────────────────────────────┼──────────┤
│    0    │           'missing.a'            │  2   │         '/tests/unit/fixtures/vue-files/file1.js'          │ 'de_DE'  │
│    1    │    "Don\\'t leave me behind!"    │  9   │         '/tests/unit/fixtures/vue-files/file1.js'          │ 'de_DE'  │
...
```

Test code should be changed to expect `1`. Am i right? It should fail if report found missing keys.

**Comment by pixari** [comment]
I have to inspect this..

**Comment by vasaeps3** [comment]
@pixari just check the format variable "ci"  in reportCommand function
![image](https://user-images.githubusercontent.com/4850895/115421057-52580080-a204-11eb-8a9b-94586de461bb.png)

**Comment by set0x** [comment]
Same problem 😭 

![image](https://user-images.githubusercontent.com/15133015/115849906-a42ba100-a425-11eb-8457-ff86cbb6e702.png)

**Comment by Roriz** [comment]
up

**Comment by vasaeps3** [comment]
@pixari When will you be able to update the package with this fix?

**Comment by pixari** [comment]
@vasaeps3 the new version has been released few minutes ago :)

**Comment by vasaeps3** [comment]
> @vasaeps3 the new version has been released few minutes ago :)

Great! Thanks a lot! Good job =)
