### ISSUE TITLE
Unable to extract literal strings

### ISSUE THREAD

**Issue by sarb00923** [pixari/vue-i18n-extract#116]
I am using pug templates and in my components. Please, have a look at the following mark-up:
![image](https://user-images.githubusercontent.com/28385551/110111792-ded66d00-7dd6-11eb-85af-1f2aa8898667.png)

I need the string to be considered as a literal one and the final extracted key in the json file should be
`App#Error Your check-in date is in the past. Please, select a valid date`

but it's considered as an object and extracted as such:
![image](https://user-images.githubusercontent.com/28385551/110111921-10e7cf00-7dd7-11eb-85d1-f3dea7a97672.png)

I hope my question and format is understandable. Thank you.

**Comment by pixari** [comment]
Hi @pascalbaljet, yes, I would be absolutely interested. It would be great!

**Comment by vricosti** [comment]
@pascalbaljet
With the next releases you will be able to specify a separator option and it will allow you to do this.

**Comment by Spittal** [comment]
Solved and tested in 2.0.0!
