### ISSUE TITLE
Arrays are detected as missing keys

### ISSUE THREAD

**Issue by existe-deja** [pixari/vue-i18n-extract#127]
I have some array entries in my translation files and they are detected as missing keys but the aren't.
Is it an intended behavior?

**Comment by pixari** [comment]
Can you provide an example?
Thank you.

**Comment by existe-deja** [comment]
Sure.

lang/en.json
```
{
  "test-list": [
    "some item",
    "another one"
  ]
}
```

pages/index.vue
```
<template>
  <h1>
    {{ $t('test-list') }}
  </h1>
</template>
```

vue-i18n-extract.config.js
```
module.exports = {
  vueFilesPath: './?(pages|components)/**/*.?(js|vue)',
  languageFilesPath: './lang/en.json',
  options: {
    output: false,
    add: false,
    dynamic: 'report'
  }
}
```

report
```
missing keys: 
┌─────────┬─────────────┬──────┬────────────────────┬──────────┐
│ (index) │    path     │ line │        file        │ language │
├─────────┼─────────────┼──────┼────────────────────┼──────────┤
│    0    │ 'test-list' │  3   │ '/pages/index.vue' │   'en'   │
└─────────┴─────────────┴──────┴────────────────────┴──────────┘
unused keys: 
┌─────────┬──────┬────────────────┬─────────────────┬──────────┐
│ (index) │ line │      path      │      file       │ language │
├─────────┼──────┼────────────────┼─────────────────┼──────────┤
│    0    │  0   │ 'test-list[0]' │ '/lang/en.json' │   'en'   │
│    1    │  1   │ 'test-list[1]' │ '/lang/en.json' │   'en'   │
└─────────┴──────┴────────────────┴─────────────────┴──────────┘
```

This is a dumb exemple because I will not translate a pure array but I use them sometimes to have list that can vary between languages.
like this:
```
<template>
  <ul>
    <li
      v-for="(item, i) in $t('test-list')"
      :key="i"
    >
      {{ item }}
    </li>
  </ul>
</template>
```

**Comment by Spittal** [comment]
Hey I ran a quick test on this with vue-i18n v9 and formatting a message as an array of strings isn't supported and doesn't work. I also looked, and this is not mentioned in their docs. 

We're pretty committed to limiting the scope of this project to vue-i18n so we wont be implementing support for string arrays.

Thanks for bringing it to our attention though.

**Comment by existe-deja** [comment]
Hi @Spittal, it looks like arrays or object are still supported but now they have to be translated through [$tm](https://vue-i18n.intlify.dev/api/composition.html#tm-key) function

**Comment by Spittal** [comment]
Hmm, interesting thanks for bringing this to my attention. I'm not really sure exactly how we'd want to report on arrays however. We can detect whether or not the key exists in the code/lang files but we don't render Vue components so we can't check to make sure that it's iterating correctly, and on the flip side we can't infer how long the arrays will be. So for now I think we might skip this— let us know if there's a particular use case for you beyond just seeing if the key exists or not.

**Comment by Spittal** [comment]
I should say, in the next release there will be support for `$tm` matching

**Comment by existe-deja** [comment]
Well, I already use arrays or object as result of translated content in my app.

For exemple I use array when I have to display a list of items that are different between locales. ie: you have to warn your users for border checks but the number of items depends if they are European or not.

I use object when it's simpler to let the responsibility to the translation on how the component is rendered. ie: An info card that can have different layout depending if it's a simple case or complex case. I translate the main key, look for the entries and render the component.

**Comment by existe-deja** [comment]
Thanks for taking this case into consideration :pray:
