### ISSUE TITLE
Leading slash in reported filenames

### ISSUE THREAD

**Issue by paulfertser** [pixari/vue-i18n-extract#129]
Hello,
This tool reports all filesystem pathes with a leading slash prepended so one can't just select and paste the whole path to edit it. Either dot (.) needs to be prepended to reference the current working directory or the leading slash should be removed altogether.
Or am I missing some rationale why it's better to show it the current way?

**Comment by Spittal** [comment]
Hey! The tool will show absolute file paths based on the your systems disc. There are no plans for reporting relative paths.

Thanks!

**Comment by paulfertser** [comment]
Hello,

On Wed, Sep 01, 2021 at 03:06:03PM -0700, Jamie Spittal wrote:
> Hey! The tool will show absolute file paths based on the your systems disc.
> There are no plans for reporting relative paths.

My problem is that the paths reported are not actually absolute. They
look like absolute because they start with a slash but in fact they do
not contain the full real path. In other words, if I copy one of the
reported paths and use "ls <that path>" command it'll say file not found.

Do I need to provide a specific example? Or am I using the tool
somehow incorrectly?

Thank you.

**Comment by Spittal** [comment]
Hey @paulfertser I have to apologize, I didn't look into this close enough. I have fixed your issue here: https://github.com/pixari/vue-i18n-extract/commit/05442cbd5f0689646d2d41770b8c27cda63443e7

It will be in the next release!

**Comment by paulfertser** [comment]
> I have fixed your issue here: 05442cb

Awesome, thank you so much, now the ticket is indeed closed :)
