### ISSUE TITLE
Improvement : add option to choose the translated value instead of empty string 

### ISSUE THREAD

**Issue by AlaaDq** [pixari/vue-i18n-extract#131]
# Improvement : add option to choose the translated value instead of empty string
  Example: After adding the missing keys I need translated value to be the same key in en-us
```json
 "name" :" " will become "name" :"name" 
 "Good" : " " will become "good" : "good"
 ```
  And so on....
  another case when using $tc('key',3)
  it better to be extracted as:
   ```json
 "key" :" " will become "key" :"key|keys" 
 ```
   because this will reduce time of adding the translation for English keyword

**Comment by Spittal** [comment]
This PR https://github.com/pixari/vue-i18n-extract/pull/136 will address this.

**Comment by Spittal** [comment]
Discussion around this issue will continue in #136
