### ISSUE TITLE
Allow key detection in brackets and parentheses

### ISSUE THREAD

**Issue by JamesBoon** [pixari/vue-i18n-extract#144]
If the translate function `t()` is used inside of brackets or parentheses, it should still be detected by vue-i18n-extract.

It would be nice if these examples would work:
```javascript
const msgList = [t('some.key')];
throw new Error(t('some.other.key'));
```

Wouldn't it be better if the regexp uses any "not word" (`\W`) character as delimiter in front of the translation function?

---

Until then, there is a (ugly) workaround: as the vue-i18n-extract regexp requires a space in front of the translation function, the following examples already work:
```javascript
const msgList = [/**/ t('some.key')];
throw new Error(/**/ t('some.other.key'));
```

**Comment by Spittal** [comment]
Love the PR, I think it's great!
