### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by chenxch** [pixari/vue-i18n-extract#145]
Thank you for writing such an excellent toolkit.

Node 14.0.0
npm 6.14.4
vue-i18n-extract report --vueFiles './path/to/your/vue-files/**/*.?(js|vue)' --languageFiles './path/to/your/language-files/*.?(json|yml|yaml|js)'
=>
vue-i18n-extract report --vueFiles ./path/to/your/vue-files/**/*.{js,vue}' --languageFiles ./path/to/your/language-files/*.{json,yml,yaml,js}'

**Comment by Spittal** [comment]
Hey sorry what is the error here?

**Comment by chenxch** [comment]
May be my environment problem `|` does not take effect, need to use` ,`.
