### ISSUE TITLE
Error: vueFiles glob has no files.

### ISSUE THREAD

**Issue by raphaelschmitz00** [pixari/vue-i18n-extract#148]
This example from the readme did not work for me:

```
{
  "scripts": {
    "vue-i18n-extract": "vue-i18n-extract report --vueFiles './path/to/your/vue-files/**/*.?(js|vue)' --languageFiles './path/to/your/language-files/*.?(json|yml|yaml|js)'"
  }
}
```

Of course, with paths adjusted
```
"vue-i18n-extract": "vue-i18n-extract report --vueFiles './src/**/*.vue' --languageFiles './src/locales/*.json'"
```

The solution was to use escaped double quotes instead of single quotes
```
"vue-i18n-extract": "vue-i18n-extract report --vueFiles \"./src/**/*.vue\" --languageFiles \"./src/locales/*.json\""
```

So it _works_, but the readme and the error message are misleading.

**Comment by Spittal** [comment]
Hey when using single quotes like this I have had to do `'./tests/fixtures/vue-files/**/*.?(vue)'` notice the `?(vue)` at the end. Perhaps the issue is that you need to add ``*.?(vue)` `*.?(json)` to the ends of targets?
