### ISSUE TITLE
Not working inside template literals when using composition API and SFC

### ISSUE THREAD

**Issue by jan-thoma** [pixari/vue-i18n-extract#158]
It looks like `vue-i18n-extract` is not working when it's used on inside template literals alongside with the composition API.
For example:

````
<script setup>

import { useI18n } from 'vue-i18n'
import { computed } from '@vue/reactivity'

const { t } = useI18n()
const text = computed(() => `${t('PURCHASE_FOR')} 99$`)

</script>
````

Is reporting unused keys.

**Comment by Spittal** [comment]
I've found this to be the case in the large app that we're using this in internally. I've written a test case for this https://github.com/pixari/vue-i18n-extract/blob/master/tests/fixtures/vue-files/edge-cases.js#L15

I've also tested with the exact code you've posted and it looks like it's working now in the next release! Let me know if the newest release solves your issue!
