### ISSUE TITLE
Report shows unused keys, even though they are used by other translations

### ISSUE THREAD

**Issue by r0kk** [pixari/vue-i18n-extract#160]
Hi, I am adding an example below. Report says that **foo** is not used, even though fooView.fooUsed is used in the code. 

Any ideas how we could solve this?

```
{
    "foo": "Foo translation",
    "fooView": {
        "fooUsed": "@:foo"
    },
}
```

Thank you in advance.

**Comment by Spittal** [comment]
Hey @r0kk is `@:` a way to reference another translation, because if so, that won't work with this tool. This tool just does static code analysis to match key names in language files to names of translations in code.
