### ISSUE TITLE
[Feature request] Support analytical data that have AST like interface 

### ISSUE THREAD

**Issue by kazupon** [pixari/vue-i18n-extract#18]
vue-i18n-extract is great projects! 👍 

I will be able to provide the useful command with vue-cli-plugin-i18n using the API exposed with vue-i18n-extract.

I think that we will be able to convey the report details to the user, If vue-i18n-extract provides analytical data supporting AST like interface (include line number and etc ...). 😸

**Comment by pixari** [comment]
Thanks @kazupon!

It won't be a problem at all.
Actually I already have the informations you mentioned.

I just have to pass them to the report.

Stay tuned :)

**Comment by pixari** [comment]
Hello @kazupon!

I fixed it: https://github.com/pixari/vue-i18n-extract/commit/712e7500962e5e28b761175f7895f148b16ccfd0

That's how the result will look like:

<img src="https://raw.githubusercontent.com/pixari/vue-i18n-extract/master/demo/screenshots/vue-i18n-extract-3.png" width="600">

<img src="https://raw.githubusercontent.com/pixari/vue-i18n-extract/master/demo/screenshots/vue-i18n-extract-4.png" width="600">

I've also update the API's documentation.

i am looking forward to hearing feedback from you. 😃

**Comment by kazupon** [comment]
Thanks!
