### ISSUE TITLE
JSON Format for languages support

### ISSUE THREAD

**Issue by kazupon** [pixari/vue-i18n-extract#19]
Currently, `AnalyzeLanguageFiles` cannot read the json language files.
https://github.com/pixari/vue-i18n-extract#analyzelanguagefiles

We often use the json format.
I hope that supporting. :)

**Comment by pixari** [comment]
Sure! I'll be easy. 
Give me a couple of days. :)

**Comment by nelson6e65** [comment]
I just wanna point this, but I had not much time to test this tool in a project I used JSON.

Also... In addition... I don't use a key-like string (`"message_title": "Título del mensaje"`) as key for the string in my JSON, but a "fallback" string as key (`"Message Title": "Título del mensaje"`) (https://github.com/kazupon/vue-i18n/issues/138#issuecomment-374757144)

**Comment by Spittal** [comment]
> Also... In addition... I don't use a key-like string (`"message_title": "Título del mensaje"`) as key for the string in my JSON, but a "fallback" string as key (`"Message Title": "Título del mensaje"`)

This is the exact situation that I use. My keys are the fall back for my translations.

**Comment by pixari** [comment]
I created the issue.
I can start working on it, or maybe someone is already take care of it? (@Spittal?)

**Comment by pixari** [comment]
Hi @kazupon!

https://github.com/pixari/vue-i18n-extract/pull/25

@Spittal just fixed this issue. 👍 👍 👍 

It's available in the latest version: 0.2.3.

We are also reviewing this PR:
https://github.com/pixari/vue-i18n-extract/pull/26

I think it adds an interesting feature.

😄

**Comment by kazupon** [comment]
Thanks!
