### ISSUE TITLE
Question: Does this work with vue 3 composition api?

### ISSUE THREAD

**Issue by TomT15** [pixari/vue-i18n-extract#216]
New guy here but I was wondering if this was originally setup for vue 2 and if it has been setup to handle vue 3

**Comment by Spittal** [comment]
Hey Tom, we use it at my company and we're fully in the composition API world. We have specific Regex patterns we look for with this tool, so as long as you aren't importing the translate functions with different names it should work.

For Example
```ts
const { t } = useI18n(); // <-- good
const { t: translate } = useI18n(); // <-- bad
```
