### ISSUE TITLE
Support for string-as-key fallbacks

### ISSUE THREAD

**Issue by pixari** [pixari/vue-i18n-extract#23]
I just wanna point this, but I had not much time to test this tool in a project I used JSON.

Also... In addition... I don't use a key-like string (`"message_title": "Título del mensaje"`) as key for the string in my JSON, but a "fallback" string as key (`"Message Title": "Título del mensaje"`) (https://github.com/kazupon/vue-i18n/issues/138#issuecomment-374757144)

_Originally posted by @nelson6e65 in https://github.com/pixari/vue-i18n-extract/issues/19#issuecomment-467687823_

and: 

"This is the exact situation that I use. My keys are the fall back for my translations." from @Spittal 
https://github.com/pixari/vue-i18n-extract/issues/19#issuecomment-467941185

**Comment by pixari** [comment]
https://github.com/pixari/vue-i18n-extract/pull/26

Done and available in 0.2.4.

😄

**Comment by nelson6e65** [comment]
Nice!
