### ISSUE TITLE
[Feature request] Support analytical language AST data

### ISSUE THREAD

**Issue by kazupon** [pixari/vue-i18n-extract#27]
I would like to support unused keys reporting of language file in vue-cli-plugin-i18n. (e.g ESLint stylish reporting like)

In about [analyzeUnusedKeys](https://github.com/pixari/vue-i18n-extract#analyzeunusedkeys), If vue-i18n-extract will provide language file AST,  I think that we will be able to convey the report details.

**Comment by pixari** [comment]
Hello @kazupon,

I can do it in 2/3 days.

😄

**Comment by pixari** [comment]
Hi everybody!
Actually I found out it is a bit more complicated than expected.

Maybe I need some support. @Spittal, would you like to have a look?

@kazupon: is it a problem if we postpone it for 2/3 weeks?

**Comment by kazupon** [comment]
@pixari 
No problem!

**Comment by pixari** [comment]
Done :)

**Comment by kazupon** [comment]
Thanks!
