### ISSUE TITLE
Vue i18n Extract in Typescript and new Repo

### ISSUE THREAD

**Issue by Spittal** [pixari/vue-i18n-extract#31]
Hi Pixari!

As I'm sure you know I've been keenly interested in this project and have been working on it for the past few days. I wanted to inform you that I have modified the tool for my purposes past the point of making a pull request.

https://github.com/Spittal/vue-i18n-extract

Some changes I've made include:

1. It's all Typescript now :tada:
2. For making publishing easier and to aid with Typescript I've added in [PikaPkg](https://www.pikapkg.com/blog/introducing-pika-pack/)
3. I've modified the CLI interface to allow for multiple commands, and added a help command. 
4. I've rewritten the way files are read and parsed to make them more consistent with one another. For example the function that reads the Vue files and the Language files will both spit out a normalized data format.
5. Using the new normalized data format, I've rewritten the diffing function. It is now 5 lines of code and no longer needs `deep-diff`
6. Re-organized the whole folder structure for easier maintenance and extension in the future.
7. Many other things!

This is obviously an enormous change to your project which is why I have put it into it's own repo. But, I'd love to see if maybe you're interested in combining our efforts into one repo. Or, if you think my new repo is too different I'd be happy to maintain it on my own.

Let me know what you think!
Spittal

**Comment by pixari** [comment]
Hello @Spittal,

I had the chance to look at your code. You made a great job.

I was also working on refactoring, but I'm not yet so far.

I think you really improved the code and added important feature and it's exactly the direction where vue-i18n-extract has to go.

I would gladly merge your changes in the original repository and add you as contributor with admin rights, so we can both proceed faster.

Let me know what you think :)

Cheers,
Pixari

**Comment by Spittal** [comment]
I'd be very interested in that!

**Comment by pixari** [comment]
Hi @Spittal,

I added you to the repository. 
Could you accept the invitation?

Thanks :)

**Comment by Spittal** [comment]
:tada:

**Comment by pixari** [comment]
@Spittal 
Now you have full access.
If you'd like, you can push your version.

If everything works, we can release the new version.

**Comment by Spittal** [comment]
Okay great, I'll push it as a branch at first, I will make sure the README is correct and that the tests are back in full worker order. We can review from there.

Thanks!
