### ISSUE TITLE
Demo doesn't work anymore

### ISSUE THREAD

**Issue by pixari** [pixari/vue-i18n-extract#33]
"npm run demo" doesn't work anymore

**Comment by pixari** [comment]
Hi @Spittal, could you have a look?

**Comment by Spittal** [comment]
Hey this is likely because the files were not compiled. I fixed this by adding `npm run build` in the demo command.

**Comment by pixari** [comment]
When I try to build i get this error: 

> pack build
sh: pack: command not found
