### ISSUE TITLE
Check Readme.md

### ISSUE THREAD

**Issue by pixari** [pixari/vue-i18n-extract#38]
Readme needs to be checked.

**Comment by Spittal** [comment]
I'll make a little checklist of all the things we show in the README.md and see if they all work.

- [ ] Check Installation
  - [ ] Yarn
  - [ ] NPM
- [ ] Check `package.json` addition (make sure it runs with `npm run vue-i18n-extract` and `yarn vue-i18n-extract`
- [ ] Test `report` command

- [ ] Install globally
- [ ] Run `report` command anywhere

- [ ] Test `-o` argument

- [ ] Test demo/test workflow (clone, build,  demo, test)

- [ ] Check for typos and grammatical errors
- [ ] Check for areas we could make the README.md more clear

Feel free of course to add or remove anything you want @pixari !

**Comment by pixari** [comment]
Perfect! Thank you!
I'll work on the checklist and also prepare the new doc (see #40 ).
Is it ok for you? 😄

**Comment by Spittal** [comment]
That works for me I'll close this and move over to the other ticket.
