### ISSUE TITLE
Circle CI needs to be updated to use Pika for publishing

### ISSUE THREAD

**Issue by Spittal** [pixari/vue-i18n-extract#39]
Hey @pixari 

While publish does exist in CircleCI it needs to run `npm run build` then actually publish what gets generated in the `./pkg` folder. The reason for this is Pika is what does all the typescript compilation as well as generating typings and the wrapper to make the tool a CLI so basically it will need to 

```
npm install
npm run build
cd pkg
npm publish
```

Thanks!

**Comment by pixari** [comment]
It should work now.
What do you think? :)

https://github.com/pixari/vue-i18n-extract/blob/master/.circleci/config.yml

**Comment by Spittal** [comment]
I made a small change, I believe you don't need to run install again, as it ran during the test job and you're mounting that to the deploy job. Then I shuffled some things around. I will give it a try now!

**Comment by Spittal** [comment]
Nope, looks like it actually does need the npm install in there. my bad! :\

**Comment by Spittal** [comment]
Having trouble getting it work... Pushing lots of builds to test everything... Will fix shortly.

**Comment by Spittal** [comment]
:tada: fixed at of `v.0.4.8`
