### ISSUE TITLE
New Documentation

### ISSUE THREAD

**Issue by pixari** [pixari/vue-i18n-extract#40]
Hi!
I think it's time to create a new *cool* documentation with Vue Press and deploy on GitHub pages. 😄 

- [ ] Build documentation with Vue Press
- [ ] Deploy it on GitHub Pages

**Comment by Spittal** [comment]
Moving over from issue #38 

- [ ] Check Installation with Yarn and NPM
- [ ] Check `package.json` addition (make sure it runs with `npm run vue-i18n-extract` and `yarn vue-i18n-extract`
- [ ] Test `report` command
- [ ] Install globally
- [ ] Run `report` command anywhere
- [ ] Test `-o` argument
- [ ] Test demo/test workflow (clone, build,  demo, test)
- [ ] Check for typos and grammatical errors
- [ ] Check for areas we could make the README.md more clear

**Comment by pixari** [comment]
Hi @Spittal!

Do you like it? https://pixari.github.io/vue-i18n-extract/

I think we have to improve it, but it's a good start.
We also have the docs in the deployment pipeline.

**Comment by pixari** [comment]
Hi @kazupon!

Do you like this kind of documentation? => https://pixari.github.io/vue-i18n-extract/

**Comment by Spittal** [comment]
Perfect, I love this! This will be a good foundation for us to add better documentation!

**Comment by kazupon** [comment]
cool!
In addition, it would be nice to have an API reference!
