### ISSUE TITLE
CLI report truncates fields

### ISSUE THREAD

**Issue by jamiechong** [pixari/vue-i18n-extract#45]
I've been looking forward to using this tool. Thanks!

I just ran it for the first time and I'm seeing a lot of ellipses in the report. It seems to show absolute paths even though I run the report using relative paths. 

`vue-i18n-extract  report -v 'src/**/*.?(js|vue)' -l 'src/locales/*.json'`

Here is a sample image of the output.

<img width="617" alt="Screenshot 2019-04-11 15 22 11" src="https://user-images.githubusercontent.com/981664/55996965-e71ae180-5c6d-11e9-9661-45507ec92886.png">

Maybe take a flag that gives me an option to  expand all columns. Or allow me to output to CSV which I can open in Excel or something that is still human readable and with all relevant info.

**Comment by Spittal** [comment]
Hi! Thanks for reporting this!

Fixed in https://github.com/pixari/vue-i18n-extract/pull/47

**Comment by jamiechong** [comment]
I took a look at the PR and note that in the screen shot it seems to truncate the first column as well. When the number exceeds `99`. Don't think your PR handles that. Is there a reason why they report must max out at 100 characters? Maybe allow a flag to set/increase this?

**Comment by nothingismagick** [comment]
Maybe a little reporting site like for code coverage could be useful... Or
a standalone electron app. If only there were a framework where you could
build both with the same codebase.

**Comment by Spittal** [comment]
For sure, I know we want to keep the scope of the tool pretty small. So it can be extended to ones use case. For example I know @kazupon is making a `vue-cli` plugin being made that's using this tool, he wouldn't need a web based report. However I will look into the cli table truncating columns.

**Comment by pixari** [comment]
@Spittal what about adding a flag to show either the full path or the filename?

Theoretically the paths could be also 200 chars long, and I don't think is a good idea to have so a wide table.

And you are totally right, this is probably not the scope. The table we show in the console log is kind of a "proof" that it works.

**Comment by civicwar** [comment]
@pixari Hello,
I've made a pull request that should be a workaround this issue.

@jamiechong If you want to get a CSV or something like that, the **vue-i18n-extract** cli has an option -o that outputs the report into a JSON file.

Best Regards,
David Fernandes

**Comment by pixari** [comment]
Well done, @civicwar!

Closed with #52
