### ISSUE TITLE
Report table column dimensions

### ISSUE THREAD

**Issue by danielstc** [pixari/vue-i18n-extract#53]
Hi very useful tool!
I encountered a small problem. When the key count is more than 2 digits, these are cut.
I solved by increasing the size of the first column in the script that generates the report.

Before
![1st_column_translation_tool](https://user-images.githubusercontent.com/32573423/62830498-34a15e00-bc10-11e9-8e0c-e77838162cee.png)

After
![translation_tool](https://user-images.githubusercontent.com/32573423/62830504-3ec35c80-bc10-11e9-98ff-4a34627f945c.png)

dan

**Comment by Spittal** [comment]
Hey Dan! Wonderful! Want to open a PR with the change you made? Thanks!

**Comment by pixari** [comment]
Hi @danielstc, it would be great if you could open a PR with your changes :)
Thank you very much
