### ISSUE TITLE
Option to disable colours on output

### ISSUE THREAD

**Issue by Soviut** [pixari/vue-i18n-extract#57]
I'm using vue-i18n-extract to generate a report as part of a CircleCI build pipeline.

I'm using the following command to output to stdout and a file which gets stored as a "build artifact".

```
npx vue-i18n-extract report -v "./**/*.?(js|vue)" -l "./locales/*.?(js|json)" | tee /tmp/i18n-report
```

Unfortunately, the stored result contains colour codes and winds up looking like this

```
[37m┌────[39m[37m┬────────────[39m[37m┬────────────────────────────────────────[39m[37m┬────────[39m[37m┬──────────────────────────────┐[39m
[37m│[39m[32m #  [39m[37m│[39m[32m Language   [39m[37m│[39m[32m File                                   [39m[37m│[39m[32m Line   [39m[37m│[39m[32m Missing i18n Entry           [39m[37m│[39m
[37m├────[39m[37m┼────────────[39m[37m┼────────────────────────────────────────[39m[37m┼────────[39m[37m┼──────────────────────────────┤[39m
```

It would be great if there was an option to disable colours in the output or if the `--output` flag supported plain text.

**Comment by Soviut** [comment]
For anyone else who encouters this, my workaround is to use `sed` to strip the colour codes.

```
npx vue-i18n-extract report -v "./**/*.?(js|vue)" -l "./locales/*.?(js|json)" \
| sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" \
| tee /tmp/i18n-report
```

**Comment by Spittal** [comment]
Will look into!

**Comment by pixari** [comment]
We definitely should make the colors optional then.
Thank @Soviut for bringing this up.

**Comment by Spittal** [comment]
Hey @Soviut, I have made PR #70  that uses the native `console.table` function. I tested with the `tee` command on mac and it seems like it solves your issue. It should be merged in soon.
