### ISSUE TITLE
Does not work when two keys exist on the same line, Regex needs to be lazy

### ISSUE THREAD

**Issue by ewohlken2** [pixari/vue-i18n-extract#66]
Example code:

```html
<span v-t="'product.priority_info'"></span><a href="/login" class="gtm-pdp-signin" v-t="'product.sign_in'"></a>
```

running vue-i18n-extract on this html returns a path of:
 ```html
product.priority_info'"></span><a href="/login" class="gtm-pdp-signin" v-t="'product.sign_in
``` 
instead of 2 seperate paths of `product.sign_in` and `product.priority_info`

Fix: In file-operations-vue.js, directiveRegExp should be `/v-t="'(.*?)'"/g` instead of `/v-t="'(.*)'"/g` 

Here are some links to regex101.com that further illustrate my point:
https://regex101.com/r/PzcT5n/1
https://regex101.com/r/DeVMfZ/1

Want me to open a PR?

**Comment by pixari** [comment]
Yes, please. It would be great if you could open a PR.
