### ISSUE TITLE
Support formatFallbackMessages

### ISSUE THREAD

**Issue by lahdekorpi** [pixari/vue-i18n-extract#72]
Is there an option to support extracting translations when using `formatFallbackMessages: true` [as documented in vue-i18n fallback documentation](https://kazupon.github.io/vue-i18n/guide/fallback.html#explicit-fallback-with-decision-maps)?

At the moment `$t("Hello World. Have a nice day!")` will get extracted to:
```json
"Hello World": {
  " Have a nice day!": ""
}
```

**Comment by Spittal** [comment]
Hello! @lahdekorpi this is a bug with how we handle keys with dots characters in them. We'll get this handled ASAP. Thanks for reporting!

**Comment by lahdekorpi** [comment]
Are there any workarounds for this?
Would it be feasible to just hack https://github.com/pixari/vue-i18n-extract/blob/master/src/report-command/language-files.ts#L42 and https://github.com/pixari/vue-i18n-extract/blob/master/src/report-command/language-files.ts#L63 to skip the dot notation part?

**Comment by louisluu** [comment]
+1

**Comment by pixari** [comment]
I'll have a look at it soon.

**Comment by guillaume-gagnaire** [comment]
Hey @pixari ! Thanks for your work ! Any idea of the release date of the formatFallbackMessages support ?

Thanks a lot !

**Comment by Spittal** [comment]
Hey this is solved in 2.0.0! There is also now a test to validate this.
