### ISSUE TITLE
Threat dynamic keys as unused

### ISSUE THREAD

**Issue by vmangelovv** [pixari/vue-i18n-extract#76]
Loop of locales returns unused keys

![image](https://user-images.githubusercontent.com/43376240/81379250-6ac52d00-9111-11ea-9787-319ebd5fcda8.png)

`<template
          v-for="(item, index) in
            Object.keys($i18n.messages[$i18n.fallbackLocale].views.FAQ.questions).length"
        >
          <expandable-block
            :key="index"
            :title="$t('views.FAQ.questions')[index].title"
          >
            <i18n
              :key="index"
              :path="views.FAQ.questions[${index}].text"
              tag="p"
            >`

**Comment by pixari** [comment]
How would you handle the locale loops?

**Comment by pdcmoreira** [comment]
I'm using this workaround for dynamic translations:
https://github.com/pixari/vue-i18n-extract/issues/46#issuecomment-676581515

Maybe you could do something similar?

**Comment by pixari** [comment]
I like the idea of a "ignore file" with a list of keys that must be ignored.

Do you have a working implementation somewhere, @pdcmoreira?

**Comment by pixari** [comment]
@vmangelovv, in the meantime you can run the program with the -d param.

**Comment by Spittal** [comment]
Dynamic key detection is shipped with 2.0.0
