### ISSUE TITLE
ENONENT error in windows

### ISSUE THREAD

**Issue by AaronHernandezPerez** [pixari/vue-i18n-extract#78]
Hi when I execute the command in windows 10 from "D:/proyect/" I get the following output

> $ vue-i18n-extract report -a -v "D:/proyect/src/**/*.?(js|vue)" -l "D:/proyect/src/i18n/*.?(js|json|yml|yaml)"
┌─────────┬───────────────────┬──────┬────────────────────────────────────────────────────────────────────┬──────────┐
│ (index) │       path        │ line │                                file                                │ language │
├─────────┼───────────────────┼──────┼────────────────────────────────────────────────────────────────────┼──────────┤
│    0    │  'totalTooltip'   │  13  │ 'D:/proyect/src/components/TotalSummary.vue' │ 'en-us'  │
│    2    │     'totals'      │  5   │ 'D:/proyect/src/components/TotalSummary.vue' │ 'index'  │
│    3    │  'totalTooltip'   │  13  │ 'D:/proyect/src/components/TotalSummary.vue' │ 'index'  │
└─────────┴───────────────────┴──────┴────────────────────────────────────────────────────────────────────┴──────────┘
┌─────────┬──────┬─────────────────────────┬────────────────────────────────────────────────────────┬──────────┐
│ (index) │ line │          path           │                          file                          │ language │
├─────────┼──────┼─────────────────────────┼────────────────────────────────────────────────────────┼──────────┤
│    0    │  0   │        'failed'         │ 'D:/proyect/src/i18n/en-us.json' │ 'en-us'  │
│    1    │  1   │        'success'        │ 'D:/proyect/src/i18n/en-us.json' │ 'en-us'  │
│    2    │  0   │        'failed'         │ 'D:/proyect/src/i18n/es-es.json' │ 'es-es'  │
│    3    │  1   │        'success'        │ 'D:/proyect/src/i18n/es-es.json' │ 'es-es'  │
│    4    │  0   │     'en-us.failed'      │  'D:/proyect/src/i18n/index.js'  │ 'index'  │
│    5    │  1   │     'en-us.success'     │  'D:/proyect/src/i18n/index.js'  │ 'index'  │
│    6    │  2   │     'en-us.totals'      │  'D:/proyect/src/i18n/index.js'  │ 'index'  │
│    2    │     'totals'      │  5   │ 'D:/proyect/src/components/TotalSummary.vue' │ 'index'  │
│    3    │  'totalTooltip'   │  13  │ 'D:/proyect/src/components/TotalSummary.vue' │ 'index'  │
└─────────┴───────────────────┴──────┴────────────────────────────────────────────────────────────────────┴──────────┘
┌─────────┬──────┬─────────────────────────┬────────────────────────────────────────────────────────┬──────────┐
│ (index) │ line │          path           │                          file                          │ language │
├─────────┼──────┼─────────────────────────┼────────────────────────────────────────────────────────┼──────────┤
│    0    │  0   │        'failed'         │ 'D:/proyect/src/i18n/en-us.json' │ 'en-us'  │
│    1    │  1   │        'success'        │ 'D:/proyect/src/i18n/en-us.json' │ 'en-us'  │
│    2    │  0   │        'failed'         │ 'D:/proyect/src/i18n/es-es.json' │ 'es-es'  │
│    3    │  1   │        'success'        │ 'D:/proyect/src/i18n/es-es.json' │ 'es-es'  │
│    4    │  0   │     'en-us.failed'      │  'D:/proyect/src/i18n/index.js'  │ 'index'  │
│    5    │  1   │     'en-us.success'     │  'D:/proyect/src/i18n/index.js'  │ 'index'  │
│    6    │  2   │     'en-us.totals'      │  'D:/proyect/src/i18n/index.js'  │ 'index'  │
│    8    │  4   │       'es.failed'       │  'D:/proyect/src/i18n/index.js'  │ 'index'  │
│    9    │  5   │      'es.success'       │  'D:/proyect/src/i18n/index.js'  │ 'index'  │
│   10    │  6   │       'es.totals'       │  'D:/proyect/src/i18n/index.js'  │ 'index'  │
│   12    │  8   │    'es.totalTooltip'    │  'D:/proyect/src/i18n/index.js'  │ 'index'  │
└─────────┴──────┴─────────────────────────┴────────────────────────────────────────────────────────┴──────────┘
(node:15512) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'D:\proyectD:\proyect\src\i18n\en-us.json'
  at Object.openSync (fs.js:458:3)
  at Object.writeFileSync (fs.js:1279:35)

For some reason when it is going to write the missing keys to en-us.json the path is malformed  ("'D:\proyectD:\proyect\src\i18n\en-us.json'") from where you execute it.

Changing the absolute paths to relative `yarn vue-i18n-extract report -a -v "./src/**/*.?(js|vue)" -l "./src/i18n/*.?(js|json|yml|yaml)"` doesn't work either

**Comment by pixari** [comment]
I can't reproduce the bug. 
Does someone has the same issue?

**Comment by mxgnr** [comment]
Hi there, 

I'm afraid the last PR broke the filename path on Linux/Unix systems (i'm on Mac OS 10.14.6).

I ran :
`vue-i18n-extract report -a -v './src/**/*.?(js|vue)' -l './src/locales/*.?(json|yaml|yml)'`

But i encountered this error :
`UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/src/locales/en.json'`

It seems to be searching the files at system root, instead of the relative "./src" path.

Rollback to 1.1.10 fixed this issue.
