### ISSUE TITLE
Fails when a translation uses formatting

### ISSUE THREAD

**Issue by ThaDaVos** [pixari/vue-i18n-extract#81]
I noticed some of my keys ending up as unused because the `$t('KEY', {FORMATS})` call seems to be unsupported.
Also my dynamic keys are ending up as missing, which they shouldn't

**Comment by pixari** [comment]
Hi @ThaDaVos!

Could you explain what do you mean with dynamic keys?

**Comment by Spittal** [comment]
Dynamic Key Detection shipped with 2.0.0
