### ISSUE TITLE
Shows npm version or ''-v, --vueFiles <vueFiles>' not specified"

### ISSUE THREAD

**Issue by wesleymostien** [pixari/vue-i18n-extract#82]
If I follow installation steps, and run this command:

```npm run vue-i18n-extract report -v './path/to/your/vue-files/**/*.?(js|vue)' -l './path/to/your/language-files/*.?(js|json|yml|yaml)'```

I just get the NPM version printed in console (6.14.6).

If I use '**--vueFiles**' : error: required option '-v, --vueFiles <vueFiles>' not specified.

Node version: 12.18.2

**Comment by wesleymostien** [comment]
Never

**Comment by karlmiles** [comment]
@wesleymostien I've got the exact same "issue" as you did.  What did you need to do in order to resolve it your side?
