### ISSUE TITLE
Use Webpack as Bundler

### ISSUE THREAD

**Issue by pixari** [pixari/vue-i18n-extract#85]
Webpack should be used to bundle the library. 

Documentation: https://webpack.js.org/guides/author-libraries/

**Comment by Spittal** [comment]
I don't know if I agree with this. While I'm a fan of Webpack, it's adds a layer of complexity that I just don't think a project with this small of a scope needs. Microbundle isn't a silver bullet, but without any configuration we support emitting types, emitting UMD bundles, and modern ESM bundles.

@pixari is there a reason you would want to move off microbundle?

**Comment by pixari** [comment]
As agreed we keep microbundle and yarn
