### ISSUE TITLE
Text review 

### ISSUE THREAD

**Issue by pixari** [pixari/vue-i18n-extract#89]
Since English isn't my mother language, I'm sure that the documentation/readme contains misspelling and grammatical errors.

It would be nice if someone could review and improve it (README.md).

**Comment by dakshayahuja** [comment]
Hey!!
I can review the README.md file as I am very fluent in English.
Please assign it to me.

**Comment by pixari** [comment]
Thank you very much, @dakshayahuja!

**Comment by dakshayahuja** [comment]
Hey, can you please add "hacktoberfest-accepted" label as then this PR will count for my progress in the event.

**Comment by pixari** [comment]
Of course!

**Comment by dakshayahuja** [comment]
Thank you so much!!!
