### ISSUE TITLE
Add missing keys in the correct order

### ISSUE THREAD

**Issue by matteo-azzolini** [pixari/vue-i18n-extract#99]
Hi,
I'm using vue-i18n-extract with `--add` option (yaml files for translations)
I noticed that the missing keys are added to the end of the file 

It would be great if the missing keys are added in the correct alphabetical order

**Comment by pixari** [comment]
Hi @matteo-azzolini,

this feature hasn't be planned, but it could be a nice improvement.

See here: https://github.com/pixari/vue-i18n-extract/issues/112
